# Generated by Django 5.1.2 on 2025-04-28 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlist_id_alter_bids_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
