# Generated by Django 5.1.2 on 2025-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
