# Generated by Django 5.1.2 on 2025-04-28 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlist_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='end_time',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 15, 43, 43, 694442, tzinfo=datetime.timezone.utc)),
        ),
    ]
