# Generated by Django 5.1.2 on 2025-04-28 16:52

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auctionlist_end_time_auctionlist_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='deadline',
            field=models.DateTimeField(default=auctions.models.get_deadline),
        ),
    ]
